/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caoym_WinRobot */

#ifndef _Included_com_caoym_WinRobot
#define _Included_com_caoym_WinRobot
#ifdef __cplusplus
extern "C" {
#endif
#undef com_caoym_WinRobot_MAX_DELAY
#define com_caoym_WinRobot_MAX_DELAY 60000L
#undef com_caoym_WinRobot_LEGAL_BUTTON_MASK
#define com_caoym_WinRobot_LEGAL_BUTTON_MASK 28L


/*
 * Class:     com_caoym_WinRobot
 * Method:    createScreenCaptureAsFileMapping
 * Signature: (Ljava/awt/Rectangle;)Lcom/caoym/WinFileMappingBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_caoym_WinRobot_createScreenCaptureAsFileMapping
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_caoym_WinRobot
 * Method:    delay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_delay
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_caoym_WinRobot
 * Method:    getAutoDelay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_caoym_WinRobot_getAutoDelay
  (JNIEnv *, jobject);

/*
 * Class:     com_caoym_WinRobot
 * Method:    getPixelColor
 * Signature: (II)Ljava/awt/Color;
 */
JNIEXPORT jobject JNICALL Java_com_caoym_WinRobot_getPixelColor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_caoym_WinRobot
 * Method:    isAutoWaitForIdle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_caoym_WinRobot_isAutoWaitForIdle
  (JNIEnv *, jobject);

/*
 * Class:     com_caoym_WinRobot
 * Method:    keyPress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_keyPress
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_caoym_WinRobot
 * Method:    keyRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_keyRelease
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_caoym_WinRobot
 * Method:    mouseMove
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_mouseMove
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_caoym_WinRobot
 * Method:    mousePress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_mousePress
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_caoym_WinRobot
 * Method:    mouseRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_mouseRelease
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_caoym_WinRobot
 * Method:    mouseWheel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_mouseWheel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_caoym_WinRobot
 * Method:    setAutoDelay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_setAutoDelay
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_caoym_WinRobot
 * Method:    setAutoWaitForIdle
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_setAutoWaitForIdle
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_caoym_WinRobot
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_caoym_WinRobot_toString
  (JNIEnv *, jobject);

/*
 * Class:     com_caoym_WinRobot
 * Method:    waitForIdle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_waitForIdle
  (JNIEnv *, jobject);

/*
 * Class:     com_caoym_WinRobot
 * Method:    captureMouseCursorAsFileMapping
 * Signature: (Ljava/awt/Point;Ljava/awt/Point;)Lcom/caoym/WinFileMappingBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_caoym_WinRobot_captureMouseCursorAsFileMapping
  (JNIEnv *, jobject, jobject, jobject,jintArray);

/*
 * Class:     com_caoym_WinRobot
 * Method:    keyType
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_keyType
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_caoym_WinRobot
 * Method:    sendCtrlAltDel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_sendCtrlAltDel
  (JNIEnv *, jobject);

/*
 * Class:     com_caoym_WinRobot
 * Method:    SetKeyboardLayout
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_setKeyboardLayout
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_caoym_WinRobot
 * Method:    CreateJNIObj
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_CreateJNIObj
  (JNIEnv *, jobject,jstring );

/*
 * Class:     com_caoym_WinRobot
 * Method:    DestroyJNIObj
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_caoym_WinRobot_DestroyJNIObj
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
